const express = require("express");
const util = require("util");
const db = require("../db");
const { getRegularTechnicalSection } = require("../utils/courseBackground");

const router = express.Router();
const queryAsync = util.promisify(db.query).bind(db);

let regularStudentExamTableChecked = false;
let regularExamFeedbackTableChecked = false;
let resultsSubmittedAtColumnChecked = false;
let resultsFeedbackColumnsChecked = false;
const REGULAR_START_GRACE_MINUTES = 10;

router.use((req, res, next) => {
    if (req.method === "OPTIONS") {
        return next();
    }
    if (!req.session?.student) {
        return res.status(401).json({ success: false, message: "Unauthorized" });
    }
    const normalizedType = String(req.session.student?.studentType || "")
        .trim()
        .toUpperCase()
        .replace(/[\s-]/g, "_");
    if (normalizedType === "WALKIN" || normalizedType === "WALK_IN") {
        return res.status(403).json({ success: false, message: "Forbidden" });
    }
    return next();
});

const countWords = (text) =>
    String(text || "")
        .trim()
        .split(/\s+/)
        .filter(Boolean).length;

const addMinutes = (dateValue, minutes) => {
    const date = new Date(dateValue);
    if (Number.isNaN(date.getTime())) return null;
    return new Date(date.getTime() + (Number(minutes || 0) * 60 * 1000));
};

const getRegularExamTiming = (regularExam, nowMs = Date.now()) => {
    const startAt = new Date(regularExam?.start_at || "");
    const durationMinutes = Math.max(1, Number(regularExam?.duration_minutes || 60) || 60);
    if (Number.isNaN(startAt.getTime())) {
        return null;
    }

    const questionUnlockAt = addMinutes(startAt, REGULAR_START_GRACE_MINUTES);
    const submissionDeadlineAt = addMinutes(questionUnlockAt, durationMinutes);
    if (!questionUnlockAt || !submissionDeadlineAt) {
        return null;
    }

    const startAtMs = startAt.getTime();
    const questionUnlockAtMs = questionUnlockAt.getTime();
    const submissionDeadlineMs = submissionDeadlineAt.getTime();
    const beforeStart = nowMs < startAtMs;
    const withinInstructionWindow = nowMs >= startAtMs && nowMs < questionUnlockAtMs;
    const withinQuestionWindow = nowMs >= questionUnlockAtMs && nowMs <= submissionDeadlineMs;

    return {
        startGraceMinutes: REGULAR_START_GRACE_MINUTES,
        questionDurationMinutes: durationMinutes,
        startAt: startAt.toISOString(),
        lateStartDeadlineAt: questionUnlockAt.toISOString(),
        questionUnlockAt: questionUnlockAt.toISOString(),
        submissionDeadlineAt: submissionDeadlineAt.toISOString(),
        startsInSeconds: beforeStart ? Math.max(0, Math.ceil((startAtMs - nowMs) / 1000)) : 0,
        unlockInSeconds: withinInstructionWindow ? Math.max(0, Math.ceil((questionUnlockAtMs - nowMs) / 1000)) : 0,
        remainingQuestionSeconds: withinQuestionWindow ? Math.max(0, Math.ceil((submissionDeadlineMs - nowMs) / 1000)) : 0,
        canStart: nowMs >= startAtMs && nowMs <= questionUnlockAtMs,
        instructionWindowActive: withinInstructionWindow,
        questionsVisible: nowMs >= questionUnlockAtMs,
        submissionClosed: nowMs > submissionDeadlineMs,
        lateStartClosed: nowMs > questionUnlockAtMs
    };
};

const ensureRegularStudentExamTable = async () => {
    if (regularStudentExamTableChecked) return;
    await queryAsync(
        `CREATE TABLE IF NOT EXISTS regular_student_exam (
            student_exam_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            student_id INT NOT NULL,
            exam_id INT NOT NULL,
            started_at TIMESTAMP NULL,
            question_set_id BIGINT NULL,
            CONSTRAINT uq_regular_student_exam UNIQUE (student_id, exam_id)
        )`
    );
    try {
        await queryAsync(`ALTER TABLE regular_student_exam ADD COLUMN started_at TIMESTAMP NULL`);
    } catch (error) {
        const msg = String(error?.message || "");
        if (
            String(error?.code || "").toUpperCase() !== "42701" &&
            !/duplicate column/i.test(msg) &&
            !/already exists/i.test(msg)
        ) {
            throw error;
        }
    }
    try {
        await queryAsync(`ALTER TABLE regular_student_exam ADD COLUMN question_set_id BIGINT NULL`);
    } catch (error) {
        const msg = String(error?.message || "");
        if (
            String(error?.code || "").toUpperCase() !== "42701" &&
            !/duplicate column/i.test(msg) &&
            !/already exists/i.test(msg)
        ) {
            throw error;
        }
    }
    regularStudentExamTableChecked = true;
};

const ensureRegularExamFeedbackTable = async () => {
    if (regularExamFeedbackTableChecked) return;
    await queryAsync(
        `CREATE TABLE IF NOT EXISTS regular_exam_feedback (
            feedback_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            student_id INT NOT NULL,
            exam_id INT NOT NULL,
            question_text TEXT NULL,
            feedback_text TEXT NOT NULL,
            submission_mode TEXT NULL,
            submitted_at TIMESTAMP NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_regular_exam_feedback UNIQUE (student_id, exam_id)
        )`
    );
    regularExamFeedbackTableChecked = true;
};

const ensureResultsSubmittedAtColumn = async () => {
    if (resultsSubmittedAtColumnChecked) return;
    try {
        await queryAsync(
            `ALTER TABLE regular_student_results
             ADD COLUMN submitted_at TIMESTAMP NULL`
        );
    } catch (error) {
        const msg = String(error?.message || "");
        if (
            String(error?.code || "").toUpperCase() !== "42701" &&
            !/duplicate column/i.test(msg) &&
            !/already exists/i.test(msg)
        ) {
            throw error;
        }
    } finally {
        resultsSubmittedAtColumnChecked = true;
    }
};

const ensureResultsFeedbackColumns = async () => {
    if (resultsFeedbackColumnsChecked) return;
    const columns = [
        { name: "feedback_text", definition: "TEXT NULL" },
        { name: "feedback_question_text", definition: "TEXT NULL" },
        { name: "feedback_submission_mode", definition: "VARCHAR(20) NULL" }
    ];
    for (const column of columns) {
        try {
            await queryAsync(
                `ALTER TABLE regular_student_results
                 ADD COLUMN ${column.name} ${column.definition}`
            );
        } catch (error) {
            const msg = String(error?.message || "");
            if (
                String(error?.code || "").toUpperCase() !== "42701" &&
                !/duplicate column/i.test(msg) &&
                !/already exists/i.test(msg)
            ) {
                throw error;
            }
        }
    }
    resultsFeedbackColumnsChecked = true;
};

const fetchLatestReadyRegularExamForCollege = async (collegeId) => {
    const rows = await queryAsync(
        `SELECT exam_id, exam_status, start_at, end_at, duration_minutes, college_id
         FROM regular_exams
         WHERE COALESCE(is_deleted, FALSE) = FALSE
           AND exam_status = 'READY'
           AND (college_id = ? OR college_id IS NULL)
         ORDER BY
             CASE WHEN college_id = ? THEN 0 ELSE 1 END,
             start_at DESC NULLS LAST,
             exam_id DESC
         LIMIT 1`
        ,
        [collegeId || null, collegeId || null]
    );
    return rows?.[0] || null;
};

const fetchActiveRegularQuestionSet = async (examId, txQuery = queryAsync) => {
    const rows = await txQuery(
        `SELECT question_set_id
         FROM regular_question_sets
         WHERE exam_id = ?
           AND set_status = 'ACTIVE'
         ORDER BY generated_at DESC, question_set_id DESC
         LIMIT 1`,
        [examId]
    );
    return Number(rows?.[0]?.question_set_id || 0) || null;
};

const ensureRegularStudentQuestionSet = async ({ studentId, examId, requestedStudentExamId = 0, txQuery = queryAsync }) => {
    await ensureRegularStudentExamTable();

    let rows = [];
    if (Number(requestedStudentExamId || 0) > 0) {
        rows = await txQuery(
            `SELECT student_exam_id, question_set_id, started_at
             FROM regular_student_exam
             WHERE student_exam_id = ?
               AND student_id = ?
               AND exam_id = ?
             LIMIT 1`,
            [requestedStudentExamId, studentId, examId]
        );
    } else {
        rows = await txQuery(
            `SELECT student_exam_id, question_set_id, started_at
             FROM regular_student_exam
             WHERE student_id = ?
               AND exam_id = ?
             LIMIT 1`,
            [studentId, examId]
        );
    }

    if (!rows?.length) {
        try {
            await txQuery(
                `INSERT INTO regular_student_exam (student_id, exam_id) VALUES (?, ?)`,
                [studentId, examId]
            );
        } catch (insertError) {
            const duplicate =
                Number(insertError?.errno) === 1062 ||
                String(insertError?.code || "").toUpperCase() === "23505" ||
                /duplicate key/i.test(String(insertError?.message || ""));
            if (!duplicate) throw insertError;
        }
        rows = await txQuery(
            `SELECT student_exam_id, question_set_id, started_at
             FROM regular_student_exam
             WHERE student_id = ?
               AND exam_id = ?
             LIMIT 1`,
            [studentId, examId]
        );
    }

    const studentExamId = Number(rows?.[0]?.student_exam_id || 0) || null;
    let questionSetId = Number(rows?.[0]?.question_set_id || 0) || null;
    if (!questionSetId) {
        questionSetId = await fetchActiveRegularQuestionSet(examId, txQuery);
        if (!questionSetId) {
            throw new Error("NO_ACTIVE_REGULAR_QUESTION_SET");
        }
    }

    await txQuery(
        `UPDATE regular_student_exam
         SET started_at = COALESCE(started_at, NOW()),
             question_set_id = COALESCE(question_set_id, ?)
         WHERE student_id = ?
           AND exam_id = ?`,
        [questionSetId, studentId, examId]
    );

    return { studentExamId, questionSetId };
};

const fetchRegularStudentAttempt = async ({ studentId, examId, requestedStudentExamId = 0, txQuery = queryAsync }) => {
    await ensureRegularStudentExamTable();
    const params = [];
    let sql =
        `SELECT student_exam_id, question_set_id, started_at
         FROM regular_student_exam
         WHERE student_id = ?
           AND exam_id = ?`;
    params.push(studentId, examId);
    if (Number(requestedStudentExamId || 0) > 0) {
        sql += ` AND student_exam_id = ?`;
        params.push(requestedStudentExamId);
    }
    sql += ` LIMIT 1`;
    const rows = await txQuery(sql, params);
    return rows?.[0] || null;
};

const loadRegularSavedAnswers = async ({ studentId, examId, questionSetId, txQuery = queryAsync }) => {
    if (!studentId || !examId || !questionSetId) return [];
    return await txQuery(
        `SELECT sa.question_id,
                sa.selected_option,
                q.question_type,
                q.section_name
         FROM regular_student_answers sa
         JOIN regular_exam_questions q
           ON q.exam_id = sa.exam_id
          AND q.question_set_id = sa.question_set_id
          AND q.question_id = sa.question_id
         WHERE sa.student_id = ?
           AND sa.exam_id = ?
           AND sa.question_set_id = ?`,
        [studentId, examId, questionSetId]
    );
};

const fetchRegularAllowedQuestionIds = async ({
    examId,
    questionSetId,
    allowedTechnicalSection,
    txQuery = queryAsync
}) => {
    if (!examId || !questionSetId) return new Set();
    const rows = await txQuery(
        `SELECT question_id
         FROM regular_exam_questions
         WHERE exam_id = ?
           AND question_set_id = ?
           AND (
               UPPER(COALESCE(section_name, '')) = 'APTITUDE'
               OR UPPER(COALESCE(section_name, '')) = UPPER(COALESCE(?, ''))
           )`,
        [examId, questionSetId, allowedTechnicalSection || null]
    );
    return new Set(
        (rows || [])
            .map((row) => Number(row?.question_id || 0))
            .filter((questionId) => questionId > 0)
    );
};

const mergeRegularSubmittedAnswers = ({ payloadAnswers = [], savedRows = [] }) => {
    const merged = new Map();

    savedRows.forEach((row) => {
        const questionId = Number(row?.question_id || 0);
        if (!questionId) return;
        const selectedOption = String(row?.selected_option || "").trim().toUpperCase();
        if (!selectedOption) return;
        merged.set(questionId, {
            question_id: questionId,
            question_type: String(row?.question_type || "MCQ").trim().toLowerCase(),
            section_name: String(row?.section_name || "").trim(),
            selected_option: selectedOption
        });
    });

    payloadAnswers.forEach((answer) => {
        const questionId = Number(answer?.question_id || 0);
        if (!questionId) return;
        const selectedOption = String(answer?.selected_option || "").trim().toUpperCase();
        if (!selectedOption) {
            merged.delete(questionId);
            return;
        }
        merged.set(questionId, {
            question_id: questionId,
            question_type: String(answer?.question_type || "MCQ").trim().toLowerCase(),
            section_name: String(answer?.section_name || "").trim(),
            selected_option: selectedOption
        });
    });

    return [...merged.values()];
};

const isRegularExamSubmitted = async (studentId, examId) => {
    const rows = await queryAsync(
        `SELECT result_id
         FROM regular_student_results
         WHERE student_id = ?
           AND exam_id = ?
         LIMIT 1`,
        [studentId, examId]
    );
    return Boolean(rows?.length);
};

router.post("/start", async (req, res) => {
    const studentId = Number(req.body?.studentId || 0);
    const examId = Number(req.body?.examId || 0);

    if (!studentId || !examId) {
        return res.status(400).json({ success: false, message: "Missing student or exam" });
    }
    if (String(studentId) !== String(req.session.student?.studentId)) {
        return res.status(403).json({ success: false, message: "Forbidden" });
    }

    try {
        const studentRows = await queryAsync(
            `SELECT status, student_type, college_id
             FROM students
             WHERE student_id = ?
             LIMIT 1`,
            [studentId]
        );
        const student = studentRows?.[0] || {};
        const isStudentActive = String(student.status || "").trim().toUpperCase() === "ACTIVE";
        if (!isStudentActive) {
            return res.status(403).json({ success: false, message: "Forbidden" });
        }

        const latestRegularExam = await fetchLatestReadyRegularExamForCollege(student.college_id);
        if (!latestRegularExam) {
            return res.status(404).json({ success: false, message: "No READY regular exam found." });
        }
        if (Number(latestRegularExam.exam_id || 0) !== examId) {
            return res.status(403).json({ success: false, message: "Only the latest regular exam can be started." });
        }

        const nowMs = Date.now();
        const timing = getRegularExamTiming(latestRegularExam, nowMs);
        if (!timing) {
            return res.status(500).json({ success: false, message: "Invalid regular exam schedule." });
        }
        if (timing.startsInSeconds > 0) {
            const startsInSeconds = timing.startsInSeconds;
            const hours = Math.floor(startsInSeconds / 3600);
            const minutes = Math.floor((startsInSeconds % 3600) / 60);
            const seconds = startsInSeconds % 60;
            const parts = [];
            if (hours > 0) parts.push(`${hours}h`);
            if (minutes > 0 || hours > 0) parts.push(`${minutes}m`);
            parts.push(`${seconds}s`);
            return res.status(409).json({
                success: false,
                code: "exam_not_started",
                startsAt: latestRegularExam.start_at,
                now: new Date(nowMs).toISOString(),
                startsInSeconds,
                lateStartDeadlineAt: timing.lateStartDeadlineAt,
                message: `Exam starts in ${parts.join(" ")}`
            });
        }
        if (timing.lateStartClosed) {
            return res.status(410).json({
                success: false,
                code: "exam_start_window_closed",
                lateStartDeadlineAt: timing.lateStartDeadlineAt,
                message: "The 10-minute start window is closed. You can no longer attend this regular exam."
            });
        }

        const regularAttempt = await ensureRegularStudentQuestionSet({ studentId, examId });
        return res.json({
            success: true,
            studentExamId: regularAttempt.studentExamId,
            timing
        });
    } catch (error) {
        if (String(error?.message || "") === "NO_ACTIVE_REGULAR_QUESTION_SET") {
            return res.status(404).json({ success: false, message: "No active regular question set found." });
        }
        console.error("Regular start exam error:", error);
        return res.status(500).json({ success: false, message: "Could not start exam" });
    }
});

router.get("/duration/:examId", async (req, res) => {
    const examId = Number(req.params.examId || 0);
    if (!examId) {
        return res.status(400).json({ success: false, message: "Invalid exam id" });
    }
    try {
        const rows = await queryAsync(
            `SELECT duration_minutes, start_at
             FROM regular_exams
             WHERE exam_id = ?
             LIMIT 1`,
            [examId]
        );
        const exam = rows?.[0] || null;
        const timing = getRegularExamTiming(exam);
        return res.json({
            success: true,
            durationMinutes: Number(exam?.duration_minutes || 0) || null,
            startGraceMinutes: REGULAR_START_GRACE_MINUTES,
            timing
        });
    } catch (error) {
        console.error("Regular exam duration lookup error:", error);
        return res.status(500).json({ success: false, message: "Could not load exam duration" });
    }
});

router.get("/attempted/:studentId/:examId", async (req, res) => {
    if (String(req.params.studentId) !== String(req.session.student.studentId)) {
        return res.status(403).json({ success: false, message: "Forbidden" });
    }
    try {
        const submitted = await isRegularExamSubmitted(req.params.studentId, req.params.examId);
        return res.json({ attempted: submitted });
    } catch (error) {
        console.error("Regular attempted lookup error:", error);
        return res.json({ attempted: false });
    }
});

router.get("/questions/:examId", async (req, res) => {
    const examIdNum = Number(req.params.examId || 0);
    if (!examIdNum) {
        return res.status(400).json({ success: false, message: "Invalid exam id" });
    }
    try {
        const studentId = Number(req.session?.student?.studentId || 0);
        const studentRows = await queryAsync(
            `SELECT status, background_type, college_id
             FROM students
             WHERE student_id = ?
             LIMIT 1`,
            [studentId]
        );
        const student = studentRows?.[0] || {};
        const isActive = String(student.status || "").trim().toUpperCase() === "ACTIVE";
        if (!isActive) {
            return res.status(403).json({ success: false, message: "Forbidden" });
        }

        const latestRegularExam = await fetchLatestReadyRegularExamForCollege(student.college_id);
        if (!latestRegularExam) {
            return res.status(404).json({ success: false, message: "No READY regular exam found." });
        }
        if (Number(latestRegularExam.exam_id || 0) !== examIdNum) {
            return res.status(403).json({ success: false, message: "Only the latest regular exam questions are accessible." });
        }

        const nowMs = Date.now();
        const timing = getRegularExamTiming(latestRegularExam, nowMs);
        if (!timing) {
            return res.status(500).json({ success: false, message: "Invalid regular exam schedule." });
        }
        if (timing.startsInSeconds > 0) {
            return res.status(409).json({
                success: false,
                code: "exam_not_started",
                startsAt: latestRegularExam.start_at,
                now: new Date(nowMs).toISOString(),
                startsInSeconds: timing.startsInSeconds,
                message: "Exam has not started yet."
            });
        }
        const existingAttempt = await fetchRegularStudentAttempt({ studentId, examId: examIdNum });
        if (!existingAttempt) {
            return res.status(403).json({ success: false, message: "Start the exam first to access the question paper." });
        }
        if (timing.instructionWindowActive) {
            return res.status(409).json({
                success: false,
                code: "instruction_window_active",
                questionUnlockAt: timing.questionUnlockAt,
                unlockInSeconds: timing.unlockInSeconds,
                message: "Instructions are active. Questions will appear after the 10-minute start window closes."
            });
        }
        if (timing.submissionClosed) {
            return res.status(410).json({ success: false, message: "Exam window is closed." });
        }

        const allowedTechnicalSection = getRegularTechnicalSection(student.background_type);
        const attempt = await ensureRegularStudentQuestionSet({
            studentId,
            examId: examIdNum
        });
        const questionSetId = attempt.questionSetId;
        const rows = await queryAsync(
            `SELECT q.*,
                    1 AS marks
             FROM regular_exam_questions q
             WHERE q.exam_id = ?
               AND q.question_set_id = ?
               AND (
                   UPPER(COALESCE(q.section_name, '')) = 'APTITUDE'
                   OR UPPER(COALESCE(q.section_name, '')) = UPPER(COALESCE(?, ''))
               )
             ORDER BY
                 CASE
                     WHEN UPPER(COALESCE(q.section_name, '')) = 'APTITUDE' THEN 1
                     WHEN UPPER(COALESCE(q.section_name, '')) = 'TECHNICAL_BASIC' THEN 2
                     WHEN UPPER(COALESCE(q.section_name, '')) = 'TECHNICAL_ADVANCED' THEN 2
                     ELSE 3
                 END,
                 q.question_id`,
            [examIdNum, questionSetId, allowedTechnicalSection || null]
        );
        return res.json(Array.isArray(rows) ? rows : []);
    } catch (error) {
        if (String(error?.message || "") === "NO_ACTIVE_REGULAR_QUESTION_SET") {
            return res.status(404).json({ success: false, message: "No active regular question set found." });
        }
        console.error("Fetch regular questions error:", error);
        return res.status(500).json({ success: false, message: "Unable to load questions." });
    }
});

router.get("/draft/:examId", async (req, res) => {
    const examId = Number(req.params.examId || 0);
    const studentId = Number(req.session?.student?.studentId || 0);
    if (!examId || !studentId) {
        return res.status(400).json({ success: false, message: "Invalid exam context" });
    }
    try {
        const attempt = await fetchRegularStudentAttempt({ studentId, examId });
        if (!attempt?.question_set_id) {
            return res.json({ success: true, drafts: [] });
        }
        const drafts = await loadRegularSavedAnswers({
            studentId,
            examId,
            questionSetId: Number(attempt.question_set_id || 0)
        });
        return res.json({ success: true, drafts });
    } catch (error) {
        console.error("Regular draft fetch error:", error);
        return res.status(500).json({ success: false, message: "Could not load saved answers." });
    }
});

router.post("/draft/autosave", async (req, res) => {
    const studentId = Number(req.session?.student?.studentId || 0);
    const bodyStudentId = Number(req.body?.studentId || 0);
    const examId = Number(req.body?.examId || 0);
    if (!studentId || !bodyStudentId || !examId) {
        return res.status(400).json({ success: false, message: "Invalid autosave payload" });
    }
    if (studentId !== bodyStudentId) {
        return res.status(403).json({ success: false, message: "Forbidden" });
    }
    try {
        const submitted = await isRegularExamSubmitted(studentId, examId);
        if (submitted) {
            return res.json({
                success: false,
                submitted: true,
                message: "Exam already submitted. Autosave is locked."
            });
        }

        const studentRows = await queryAsync(
            `SELECT status, college_id, background_type
             FROM students
             WHERE student_id = ?
             LIMIT 1`,
            [studentId]
        );
        const regularStudent = studentRows?.[0] || {};
        const latestRegularExam = await fetchLatestReadyRegularExamForCollege(regularStudent.college_id);
        if (!latestRegularExam || Number(latestRegularExam.exam_id || 0) !== examId) {
            return res.status(403).json({ success: false, message: "Autosave is allowed only for the latest regular exam." });
        }

        const attempt = await ensureRegularStudentQuestionSet({ studentId, examId });
        const questionSetId = Number(attempt.questionSetId || 0);
        const allowedTechnicalSection = getRegularTechnicalSection(regularStudent.background_type);
        const allowedQuestionIds = await fetchRegularAllowedQuestionIds({
            examId,
            questionSetId,
            allowedTechnicalSection
        });
        const payloadAnswers = Array.isArray(req.body?.answers) ? req.body.answers : [];
        const validAnswers = payloadAnswers
            .filter((answer) => String(answer?.question_type || "MCQ").trim().toUpperCase() === "MCQ")
            .map((answer) => ({
                question_id: Number(answer?.question_id || 0),
                selected_option: String(answer?.selected_option || "").trim().toUpperCase()
            }))
            .filter((answer) =>
                answer.question_id > 0 &&
                allowedQuestionIds.has(answer.question_id) &&
                ["A", "B", "C", "D"].includes(answer.selected_option)
            );

        await db.withTransaction(async (txQuery) => {
            await txQuery(
                `DELETE FROM regular_student_answers
                 WHERE student_id = ?
                   AND exam_id = ?
                   AND question_set_id = ?`,
                [studentId, examId, questionSetId]
            );
            for (const answer of validAnswers) {
                await txQuery(
                    `INSERT INTO regular_student_answers
                     (student_id, question_id, selected_option, exam_id, question_set_id)
                     VALUES (?, ?, ?, ?, ?)`,
                    [studentId, answer.question_id, answer.selected_option, examId, questionSetId]
                );
            }
        });

        return res.json({ success: true, saved: validAnswers.length });
    } catch (error) {
        console.error("Regular autosave error:", error);
        return res.status(500).json({ success: false, message: "Could not autosave answers" });
    }
});

router.post("/submit", async (req, res) => {
    const { studentId, examId, answers, studentExamId } = req.body;
    const submittedAnswers = Array.isArray(answers) ? answers : [];
    const requestedForceSubmit = Boolean(req.body?.forceSubmit);
    const requestedForceReason = String(req.body?.forceReason || "").trim().toUpperCase();
    let autoSubmitReason =
        requestedForceSubmit && (requestedForceReason === "TIME_OVER" || requestedForceReason === "VIOLATION")
            ? (requestedForceReason === "VIOLATION" ? "VIOLATION_LIMIT" : "TIME_OVER")
            : null;

    if (String(studentId) !== String(req.session.student.studentId)) {
        return res.status(403).json({ success: false, message: "Forbidden" });
    }

    try {
        const examIdNum = Number(examId || 0);
        const requestedStudentExamId = Number(studentExamId || 0);
        if (!examIdNum) {
            return res.status(400).json({ success: false, message: "Missing student or exam" });
        }

        const alreadySubmitted = await isRegularExamSubmitted(Number(studentId), examIdNum);
        if (alreadySubmitted) {
            return res.json({ success: true, alreadySubmitted: true, message: "Exam already submitted" });
        }

        const invalidAnswer = submittedAnswers.find((answer) => {
            const qType = String(answer?.question_type || "MCQ").trim().toUpperCase();
            const hasDescriptive = String(answer?.descriptive_answer || "").trim().length > 0;
            const hasCode = String(answer?.code || "").trim().length > 0;
            return qType !== "MCQ" || hasDescriptive || hasCode;
        });
        if (invalidAnswer) {
            return res.status(400).json({
                success: false,
                message: "Regular exams accept only Aptitude/Technical MCQ answers."
            });
        }

        const regularStudentRows = await queryAsync(
            `SELECT status, college_id, background_type
             FROM students
             WHERE student_id = ?
             LIMIT 1`,
            [studentId]
        );
        const regularStudent = regularStudentRows?.[0] || {};
        const isStudentActive = String(regularStudent.status || "").trim().toUpperCase() === "ACTIVE";
        if (!isStudentActive) {
            return res.status(403).json({ success: false, message: "Forbidden" });
        }

        const latestRegularExam = await fetchLatestReadyRegularExamForCollege(regularStudent.college_id);
        if (!latestRegularExam) {
            return res.status(404).json({ success: false, message: "No READY regular exam found." });
        }
        if (Number(latestRegularExam.exam_id || 0) !== examIdNum) {
            return res.status(403).json({ success: false, message: "Submit is allowed only for the latest regular exam." });
        }

        const regularTiming = getRegularExamTiming(latestRegularExam, Date.now());
        if (!regularTiming) {
            return res.status(500).json({ success: false, message: "Invalid regular exam schedule." });
        }
        if (regularTiming.startsInSeconds > 0) {
            return res.status(400).json({ success: false, message: "Exam has not started yet." });
        }

        const regularAttempt = await ensureRegularStudentQuestionSet({
            studentId,
            examId: examIdNum,
            requestedStudentExamId
        });
        let regularQuestionSetId = regularAttempt.questionSetId;
        let effectiveStudentExamId = regularAttempt.studentExamId;

        const existingAttempt = await fetchRegularStudentAttempt({
            studentId,
            examId: examIdNum,
            requestedStudentExamId
        });
        if (!existingAttempt) {
            return res.status(403).json({ success: false, message: "Start the exam first to submit." });
        }

        regularQuestionSetId = Number(existingAttempt?.question_set_id || regularQuestionSetId || 0) || null;
        const allowedTechnicalSection = getRegularTechnicalSection(regularStudent.background_type);
        if (regularTiming.instructionWindowActive) {
            return res.status(400).json({ success: false, message: "Question paper is not unlocked yet." });
        }
        if (regularTiming.submissionClosed) {
            autoSubmitReason = autoSubmitReason || "TIME_OVER";
        }

        const savedRows = await loadRegularSavedAnswers({
            studentId: Number(studentId),
            examId: examIdNum,
            questionSetId: regularQuestionSetId
        });
        const effectiveAnswers = mergeRegularSubmittedAnswers({
            payloadAnswers: submittedAnswers,
            savedRows
        });
        const allowedQuestionIds = await fetchRegularAllowedQuestionIds({
            examId: examIdNum,
            questionSetId: regularQuestionSetId,
            allowedTechnicalSection
        });
        const validatedAnswers = effectiveAnswers.filter((answer) =>
            allowedQuestionIds.has(Number(answer?.question_id || 0))
        );

        if (!validatedAnswers.length) {
            return res.status(400).json({ success: false, message: "No answers available to submit." });
        }

        await db.withTransaction(async (txQuery) => {
            await txQuery(
                `DELETE FROM regular_student_answers
                 WHERE student_id = ?
                   AND exam_id = ?
                   AND question_set_id = ?`,
                [studentId, examIdNum, regularQuestionSetId]
            );

            for (const answer of validatedAnswers) {
                const questionType = String(answer?.question_type || "MCQ").toUpperCase();
                if (questionType !== "MCQ") continue;
                await txQuery(
                    `INSERT INTO regular_student_answers
                     (student_id, question_id, selected_option, exam_id, question_set_id)
                     VALUES (?, ?, ?, ?, ?)`,
                    [
                        studentId,
                        answer.question_id,
                        answer.selected_option,
                        examIdNum,
                        regularQuestionSetId
                    ]
                );
            }

            await ensureResultsSubmittedAtColumn();
            await txQuery(
                `DELETE FROM regular_student_results
                 WHERE student_id = ?
                   AND exam_id = ?`,
                [studentId, examIdNum]
            );
            await txQuery(
                `INSERT INTO regular_student_results (student_id, exam_id, attempt_status, submitted_at, question_set_id)
                 VALUES (?, ?, 'SUBMITTED', NOW(), ?)`,
                [studentId, examIdNum, regularQuestionSetId]
            );
            await txQuery(
                `UPDATE students
                 SET status = 'INACTIVE'
                 WHERE student_id = ?`,
                [studentId]
            );
        });

        return res.json({
            success: true,
            message:
                autoSubmitReason === "TIME_OVER"
                    ? "Exam auto-submitted from latest saved answers after time over."
                    : (autoSubmitReason === "VIOLATION_LIMIT"
                        ? "Exam auto-submitted due to violation limit."
                        : "Exam submitted successfully"),
            studentExamId: effectiveStudentExamId,
            examId: examIdNum,
            autoSubmitted: Boolean(autoSubmitReason),
            reason: autoSubmitReason
        });
    } catch (error) {
        if (String(error?.message || "") === "NO_ACTIVE_REGULAR_QUESTION_SET") {
            return res.status(404).json({ success: false, message: "No active regular question set found." });
        }
        console.error("Regular submit exam error:", error);
        return res.status(500).json({ success: false, message: "Submission failed" });
    }
});

router.post("/feedback", async (req, res) => {
    const studentId = Number(req.session?.student?.studentId || 0);
    const bodyStudentId = Number(req.body?.studentId || 0);
    const examId = Number(req.body?.examId || 0);
    const feedbackText = String(req.body?.feedbackText || "").trim();
    const questionText = String(req.body?.questionText || "").trim();
    const modeRaw = String(req.body?.submissionMode || "MANUAL").trim().toUpperCase();
    const submissionMode = modeRaw === "AUTO_SUBMIT" ? "AUTO_SUBMIT" : "MANUAL";

    if (!studentId || !bodyStudentId || !examId) {
        return res.status(400).json({ success: false, message: "Missing required feedback context." });
    }
    if (studentId !== bodyStudentId) {
        return res.status(403).json({ success: false, message: "Forbidden" });
    }
    if (!feedbackText) {
        return res.status(400).json({ success: false, message: "Feedback is required." });
    }
    if (countWords(feedbackText) > 100) {
        return res.status(400).json({ success: false, message: "Feedback cannot exceed 100 words." });
    }

    try {
        const regularExamRows = await queryAsync(
            `SELECT exam_id
             FROM regular_exams
             WHERE exam_id = ?
             LIMIT 1`,
            [examId]
        );
        if (!regularExamRows?.length) {
            return res.status(400).json({ success: false, message: "Invalid exam id." });
        }

        const submittedRows = await queryAsync(
            `SELECT 1
             FROM regular_student_results
             WHERE student_id = ?
               AND exam_id = ?
             LIMIT 1`,
            [studentId, examId]
        );
        if (!submittedRows?.length) {
            return res.status(400).json({ success: false, message: "Feedback can be submitted only after exam submission." });
        }

        await ensureResultsFeedbackColumns();
        await queryAsync(
            `UPDATE regular_student_results
             SET feedback_question_text = ?,
                 feedback_text = ?,
                 feedback_submission_mode = ?
             WHERE student_id = ?
               AND exam_id = ?`,
            [
                questionText || "Tell us about the exam, question quality, and overall difficulty.",
                feedbackText,
                submissionMode
                ,
                studentId,
                examId
            ]
        );

        return res.json({ success: true });
    } catch (error) {
        console.error("Regular feedback save error:", error);
        return res.status(500).json({ success: false, message: "Could not save feedback." });
    }
});

router.post("/result", async (req, res) => {
    const { studentId, examId } = req.body;
    if (!studentId || !examId) {
        return res.json({ success: false, message: "Missing student or exam" });
    }
    if (String(studentId) !== String(req.session.student.studentId)) {
        return res.status(403).json({ success: false, message: "Forbidden" });
    }

    try {
        const bgRows = await queryAsync(
            `SELECT s.background_type,
                    COALESCE(r.question_set_id, rse.question_set_id) AS question_set_id
             FROM students s
             LEFT JOIN regular_student_results r
               ON r.student_id = s.student_id
              AND r.exam_id = ?
             LEFT JOIN regular_student_exam rse
               ON rse.student_id = s.student_id
              AND rse.exam_id = ?
             WHERE s.student_id = ?
             LIMIT 1`,
            [examId, examId, studentId]
        );
        const allowedTechnicalSection = getRegularTechnicalSection(bgRows?.[0]?.background_type);
        const questionSetId = Number(bgRows?.[0]?.question_set_id || 0) || null;
        if (!questionSetId) {
            return res.json({ success: false, message: "Regular question set not found" });
        }

        const totalRows = await queryAsync(
            `SELECT COUNT(*) AS total
             FROM regular_exam_questions
             WHERE exam_id = ?
               AND question_set_id = ?
               AND (
                   UPPER(COALESCE(section_name, '')) = 'APTITUDE'
                   OR UPPER(COALESCE(section_name, '')) = UPPER(COALESCE(?, ''))
               )`,
            [examId, questionSetId, allowedTechnicalSection || null]
        );
        const total = Number(totalRows?.[0]?.total || 0);
        if (!total) {
            return res.json({ success: false, message: "No regular exam questions found" });
        }

        const correctRows = await queryAsync(
            `SELECT COUNT(*) AS correct
             FROM regular_student_answers sa
             JOIN regular_exam_questions q
               ON sa.question_id = q.question_id
              AND q.question_set_id = COALESCE(sa.question_set_id, ?)
             WHERE sa.student_id = ?
               AND sa.exam_id = ?
               AND sa.selected_option = q.correct_answer
               AND COALESCE(sa.question_set_id, ?) = ?
               AND (
                   UPPER(COALESCE(q.section_name, '')) = 'APTITUDE'
                   OR UPPER(COALESCE(q.section_name, '')) = UPPER(COALESCE(?, ''))
               )`,
            [questionSetId, studentId, examId, questionSetId, questionSetId, allowedTechnicalSection || null]
        );
        const correct = Number(correctRows?.[0]?.correct || 0);
        const scorePercent = total > 0 ? Number(((correct / total) * 100).toFixed(2)) : 0;
        return res.json({
            success: true,
            totalMarks: `${correct}/${total}`,
            scorePercent
        });
    } catch (error) {
        console.error("Regular result lookup error:", error);
        return res.json({ success: false, message: "Server error" });
    }
});

module.exports = router;
